#! /usr/bin/env bash 
echo "I am creating your bucket now !"

#type in console
#./S3/bashScripts/createBucket example-ms-ms33

# check for a bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. There needs to be a bucket name ../--bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME --region ap-northeast-3 --create-bucket-configuration LocationConstraint=ap-northeast-3 \
--query Location