#! /usr/bin/env bash 
echo "I am deleting your backet !"

#type in console
#./S3/bashScripts/deleteBucket example-ms-ms33

if [ -z "$1" ]; then
    echo "No bucket name provided. There needs to be a bucket name ../--bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket --bucket $BUCKET_NAME --region ap-northeast-3 \