#! /usr/bin/env bash 

echo "I am listing your objects now !"

#type in console
#./S3/bashScripts/listObjects example-ms-ms33

# check for a bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. There needs to be a bucket name ../--bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket $BUCKET_NAME 