AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role for us to Assume and resource we will have access to
Paramaters:
  BucketName:
    Type: String
    Default: "sts-fun-ms-22"
Resources: 
  STSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"		 	 	 
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"		 	 	 
            Statement:
              - Effect: Allow
                Action: '*'    #means allow for all actions
                Resource: "arn:aws:s3:::${BucketName}"  #in arn format