Resources:
  # https://docs.aws.amazon.com/cli/latest/reference/quicksight/list-iam-policy-assignments.html
  MyUser: 
    Type: AWS::IAM::User
    Properties:
      #UserName: 'my-cool-user'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Policies:
        - PolicyName: MyCoolPolicy
        - PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Sid: IamListAccess
                Effect: Allow
                Action: 
                - 'iam:ListRoles'
                - 'iam:ListUsers'
                Resource: '*' 

  MyInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyInlinePolicyMario
      PolicyDocument:
        Version: "2012-10-17"		 	 	 
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Users:
      - !Ref MyUser
  MySecondInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MySecondInlinePolicyMario
      PolicyDocument:
        Version: "2012-10-17"		 	 	 
        Statement:
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'
      Users:
      - !Ref MyUser

