#! /usr/bin/env bash 

set -e

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region ap-northeast-3 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc3}]' \
--output json \
--query Vpc.VpcId)

echo "VPC ID: $VPC_ID"

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

echo "IGW ID : $IGW_ID"

aws ec2 attach-internet-gateway --internet-gateway-id igw-0adfd1e665f40a97c --vpc-id vpc-07bef0696f073010c